In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
tourism = pd.read_csv("../data/raw/tourism_data.csv")

hotels = pd.read_csv("../data/raw/hotels_data.csv")

flights = pd.read_csv("../data/raw/flights.csv")

flight_cost = pd.read_csv("../data/raw/flight_cost.csv")

In [3]:
print("Tourism :", tourism.shape)
print("Hotels :", hotels.shape)
print("Flights :", flights.shape)
print("Flight Cost :", flight_cost.shape)

Tourism : (92, 12)
Hotels : (1101, 13)
Flights : (33734, 11)
Flight Cost : (1423, 3)

In [4]:
def dataset_summary(df, name):

    print("=" * 70)
    print(f"{name.upper()} DATASET")
    print("=" * 70)

    print(f"\nShape: {df.shape}")

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())


    print("\nFirst 5 Rows:")
    display(df.head())

In [5]:
dataset_summary(tourism, "Tourism")

======================================================================
TOURISM DATASET
======================================================================

Shape: (92, 12)

Columns:
['Destination', 'State', 'Category', 'Best Season', 'Average Budget', 'Recommended Trip Duration', 'Latitude', 'Longitude', 'Nearest Airport', 'Popularity', 'Family Friendly', 'Adventure Score']

Data Types:
Destination                      str
State                            str
Category                         str
Best Season                      str
Average Budget                 int64
Recommended Trip Duration      int64
Latitude                     float64
Longitude                    float64
Nearest Airport                  str
Popularity                       str
Family Friendly                  str
Adventure Score                int64
dtype: object

Missing Values:
Destination                   0
State                         0
Category                      0
Best Season                   0
Average Budget                0
Recommended Trip Duration     0
Latitude                     92
Longitude                    92
Nearest Airport               0
Popularity                    0
Family Friendly               0
Adventure Score               0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,Destination,State,Category,Best Season,Average Budget,Recommended Trip Duration,Latitude,Longitude,Nearest Airport,Popularity,Family Friendly,Adventure Score
0,Goa,Goa,Beach,Nov-Feb,30000,4,NaN,NaN,Goa Airport,High,Yes,6
1,Ladakh (Leh),Ladakh,Mountain,Mar-Jun,35000,5,NaN,NaN,Ladakh Airport,High,Yes,9
2,Jaipur,Rajasthan,Heritage,Oct-Mar,22000,3,NaN,NaN,Jaipur Airport,High,Yes,3
3,Varanasi (Kashi),Uttar Pradesh,Spiritual,Oct-Mar,18000,2,NaN,NaN,Varanasi Airport,High,Yes,2
4,Agra,Uttar Pradesh,Heritage,Oct-Mar,22000,3,NaN,NaN,Agra Airport,High,Yes,3

In [6]:
dataset_summary(hotels, "Hotels")

======================================================================
HOTELS DATASET
======================================================================

Shape: (1101, 13)

Columns:
['Hotel_Name', 'Hotel_Rating', 'City', 'Feature_1', 'Feature_2', 'Feature_3', 'Feature_4', 'Feature_5', 'Feature_6', 'Feature_7', 'Feature_8', 'Feature_9', 'Hotel_Price']

Data Types:
Hotel_Name          str
Hotel_Rating    float64
City                str
Feature_1           str
Feature_2           str
Feature_3           str
Feature_4           str
Feature_5           str
Feature_6           str
Feature_7           str
Feature_8           str
Feature_9           str
Hotel_Price     float64
dtype: object

Missing Values:
Hotel_Name      0
Hotel_Rating    0
City            0
Feature_1       0
Feature_2       0
Feature_3       0
Feature_4       0
Feature_5       0
Feature_6       0
Feature_7       0
Feature_8       0
Feature_9       0
Hotel_Price     0
dtype: int64

Duplicate Rows:
18

First 5 Rows:

,Hotel_Name,Hotel_Rating,City,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Hotel_Price
0,Crowne Plaza Kochi,4.6,kochi,5-star hotel,Free breakfast,Free Wi-Fi,Free parking,Pool,Hot tub,Air conditioning,Fitness center,Spa,8854.0
1,Trident Hotel Cochin,4.5,kochi,5-star hotel,Free breakfast,Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Spa,Restaurant,6441.0
2,The Galaxy Suites,3.8,kochi,Apartment,Sleeps 10,Free parking,Free Wi-Fi,No air conditioning,No airport shuttle,No beach access,No elevator,No fireplace,831.0
3,The Renai cochin,4.2,kochi,4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Spa,Bar,2768.0
4,Ramada by Wyndham Kochi,4.5,kochi,5-star hotel,Breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Spa,Bar,8938.0

In [7]:
dataset_summary(flights, "Flights")

======================================================================
FLIGHTS DATASET
======================================================================

Shape: (33734, 11)

Columns:
['airline', 'flightNumber', 'origin', 'destination', 'daysOfWeek', 'scheduledDepartureTime', 'scheduledArrivalTime', 'timezone', 'validFrom', 'validTo', 'lastUpdated']

Data Types:
airline                   str
flightNumber              str
origin                    str
destination               str
daysOfWeek                str
scheduledDepartureTime    str
scheduledArrivalTime      str
timezone                  str
validFrom                 str
validTo                   str
lastUpdated               str
dtype: object

Missing Values:
airline                   0
flightNumber              0
origin                    0
destination               0
daysOfWeek                0
scheduledDepartureTime    0
scheduledArrivalTime      0
timezone                  0
validFrom                 0
validTo                   0
lastUpdated               0
dtype: int64

Duplicate Rows:
118

First 5 Rows:

,airline,flightNumber,origin,destination,daysOfWeek,scheduledDepartureTime,scheduledArrivalTime,timezone,validFrom,validTo,lastUpdated
0,GoAir,572,Goa,Hyderabad,"Thursday,Friday,Saturday",17:25,18:40,2021-03-27,2020-10-25,2021-03-27,2025-07-16
1,GoAir,301,Goa,Delhi,Saturday,12:00,14:45,2022-10-23,2022-03-27,2022-10-23,2025-07-16
2,GoAir,733,Goa,Nagpur,Saturday,12:10,13:40,2020-10-18,2020-03-29,2020-10-18,2025-07-16
3,GoAir,667,Goa,Lucknow,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",06:10,09:10,2019-10-26,2019-05-01,2019-10-26,2025-07-16
4,GoAir,247,Goa,Mumbai,Saturday,11:00,12:30,2022-03-20,2021-10-31,2022-03-20,2025-07-16

In [8]:
dataset_summary(flight_cost, "Flight Cost")

======================================================================
FLIGHT COST DATASET
======================================================================

Shape: (1423, 3)

Columns:
['origin', 'destination', 'avg_flight_cost_inr']

Data Types:
origin                   str
destination              str
avg_flight_cost_inr    int64
dtype: object

Missing Values:
origin                 0
destination            0
avg_flight_cost_inr    0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

  origin destination  avg_flight_cost_inr
0    Goa   Hyderabad                 3900
1    Goa       Delhi                 3100
2    Goa      Nagpur                 3400
3    Goa     Lucknow                 3000
4    Goa      Mumbai                 4000

In [9]:
hotels[hotels.duplicated()]

,Hotel_Name,Hotel_Rating,City,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Hotel_Price
5,The Renai cochin,4.2,kochi,4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Spa,Bar,2768.0
88,Sunny's World,4.2,pune,Free breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Restaurant,Kitchen,Full-service laundry,Accessible,4549.0
246,"Country Inn & Suites by Radisson, Bengaluru He...",4.1,bangalore,4-star hotel,Breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Spa,Bar,4480.0
315,Hotel Gargee Grand | Best Hotel in Patna,4.1,patna,4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Restaurant,Room service,4956.0
420,Best Western Bliss,4.1,kanpur,3-star hotel,Free breakfast,Free Wi-Fi,Free parking,Air conditioning,Pet-friendly,Restaurant,Room service,Kitchen,3300.0
434,Little Chef Hotel,4.3,kanpur,3-star hotel,Free breakfast,Wi-Fi,Paid parking,Air conditioning,Fitness center,Bar,Restaurant,Room service,3679.0
500,Hotel Ganga Sagar,4.3,mangalore,Free breakfast,Free Wi-Fi,Pool,Air conditioning,Restaurant,Room service,Full-service laundry,Kid-friendly,Smoke-free,1348.0
601,Hotel Ambience,3.9,gwalior,3-star hotel,Free breakfast,Wi-Fi,Free parking,Pool,Air conditioning,Restaurant,Room service,Airport shuttle,2191.0
628,Hotel Rangoli Pearl,4.1,amravati,1-star hotel,Free breakfast,Free Wi-Fi,Paid parking,Pool,Air conditioning,Restaurant,Room service,Airport shuttle,3130.0
634,"The Peerless Inn, Durgapur",4.0,durgapur,3-star hotel,Free breakfast,Free Wi-Fi,Free parking,Air conditioning,Fitness center,Restaurant,Room service,Kitchen,2589.0
647,Morvee Hotels Durgapur,4.4,durgapur,Free breakfast,Free Wi-Fi,Paid parking,Spa,Restaurant,Room service,Kitchen,Airport shuttle,Full-service laundry,2245.0
654,Treebo Trend Winsome Banquet And Resort,4.6,ranchi,Free breakfast,Free Wi-Fi,Paid parking,Pool,Restaurant,Room service,Kitchen,Full-service laundry,Business center,2304.0
820,Hotel Vennington Court,4.0,raipur,4-star hotel,Breakfast,Free Wi-Fi,Free parking,Pool,Hot tub,Air conditioning,Fitness center,Spa,3297.0
948,Hotel The Grand Vinayak,4.3,gandhinagar,Breakfast,Free Wi-Fi,Free parking,Air conditioning,Restaurant,Room service,Full-service laundry,Accessible,Smoke-free,2034.0
961,Hotel Om Inn,4.9,gandhinagar,0,0,0,0,0,0,0,0,0,2240.0
989,Hotel Four Element,4.4,varanasi,Free breakfast,Free Wi-Fi,Free parking,Pool,Restaurant,Room service,Full-service laundry,Accessible,0,3566.0
1033,Hotel Samudra,3.9,kanyakumari,3-star hotel,Free breakfast,Free Wi-Fi,Paid parking,Pool,Air conditioning,Beach access,Kitchen,Airport shuttle,2019.0
1099,Clafouti Beach Resort,4.1,varkala,3-star hotel,Breakfast,Free Wi-Fi,Free parking,Air conditioning,Beach access,Restaurant,Room service,Airport shuttle,4556.0

In [10]:
hotel_duplicates = hotels[hotels.duplicated(keep=False)]
hotel_duplicates.sort_values(by=hotels.columns.tolist())

,Hotel_Name,Hotel_Rating,City,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Hotel_Price
416,Best Western Bliss,4.1,kanpur,3-star hotel,Free breakfast,Free Wi-Fi,Free parking,Air conditioning,Pet-friendly,Restaurant,Room service,Kitchen,3300.0
420,Best Western Bliss,4.1,kanpur,3-star hotel,Free breakfast,Free Wi-Fi,Free parking,Air conditioning,Pet-friendly,Restaurant,Room service,Kitchen,3300.0
1081,Clafouti Beach Resort,4.1,varkala,3-star hotel,Breakfast,Free Wi-Fi,Free parking,Air conditioning,Beach access,Restaurant,Room service,Airport shuttle,4556.0
1099,Clafouti Beach Resort,4.1,varkala,3-star hotel,Breakfast,Free Wi-Fi,Free parking,Air conditioning,Beach access,Restaurant,Room service,Airport shuttle,4556.0
244,"Country Inn & Suites by Radisson, Bengaluru He...",4.1,bangalore,4-star hotel,Breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Spa,Bar,4480.0
246,"Country Inn & Suites by Radisson, Bengaluru He...",4.1,bangalore,4-star hotel,Breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Spa,Bar,4480.0
591,Hotel Ambience,3.9,gwalior,3-star hotel,Free breakfast,Wi-Fi,Free parking,Pool,Air conditioning,Restaurant,Room service,Airport shuttle,2191.0
601,Hotel Ambience,3.9,gwalior,3-star hotel,Free breakfast,Wi-Fi,Free parking,Pool,Air conditioning,Restaurant,Room service,Airport shuttle,2191.0
969,Hotel Four Element,4.4,varanasi,Free breakfast,Free Wi-Fi,Free parking,Pool,Restaurant,Room service,Full-service laundry,Accessible,0,3566.0
989,Hotel Four Element,4.4,varanasi,Free breakfast,Free Wi-Fi,Free parking,Pool,Restaurant,Room service,Full-service laundry,Accessible,0,3566.0
485,Hotel Ganga Sagar,4.3,mangalore,Free breakfast,Free Wi-Fi,Pool,Air conditioning,Restaurant,Room service,Full-service laundry,Kid-friendly,Smoke-free,1348.0
500,Hotel Ganga Sagar,4.3,mangalore,Free breakfast,Free Wi-Fi,Pool,Air conditioning,Restaurant,Room service,Full-service laundry,Kid-friendly,Smoke-free,1348.0
308,Hotel Gargee Grand | Best Hotel in Patna,4.1,patna,4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Restaurant,Room service,4956.0
315,Hotel Gargee Grand | Best Hotel in Patna,4.1,patna,4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Restaurant,Room service,4956.0
942,Hotel Om Inn,4.9,gandhinagar,0,0,0,0,0,0,0,0,0,2240.0
961,Hotel Om Inn,4.9,gandhinagar,0,0,0,0,0,0,0,0,0,2240.0
617,Hotel Rangoli Pearl,4.1,amravati,1-star hotel,Free breakfast,Free Wi-Fi,Paid parking,Pool,Air conditioning,Restaurant,Room service,Airport shuttle,3130.0
628,Hotel Rangoli Pearl,4.1,amravati,1-star hotel,Free breakfast,Free Wi-Fi,Paid parking,Pool,Air conditioning,Restaurant,Room service,Airport shuttle,3130.0
1023,Hotel Samudra,3.9,kanyakumari,3-star hotel,Free breakfast,Free Wi-Fi,Paid parking,Pool,Air conditioning,Beach access,Kitchen,Airport shuttle,2019.0
1033,Hotel Samudra,3.9,kanyakumari,3-star hotel,Free breakfast,Free Wi-Fi,Paid parking,Pool,Air conditioning,Beach access,Kitchen,Airport shuttle,2019.0
943,Hotel The Grand Vinayak,4.3,gandhinagar,Breakfast,Free Wi-Fi,Free parking,Air conditioning,Restaurant,Room service,Full-service laundry,Accessible,Smoke-free,2034.0
948,Hotel The Grand Vinayak,4.3,gandhinagar,Breakfast,Free Wi-Fi,Free parking,Air conditioning,Restaurant,Room service,Full-service laundry,Accessible,Smoke-free,2034.0
813,Hotel Vennington Court,4.0,raipur,4-star hotel,Breakfast,Free Wi-Fi,Free parking,Pool,Hot tub,Air conditioning,Fitness center,Spa,3297.0
820,Hotel Vennington Court,4.0,raipur,4-star hotel,Breakfast,Free Wi-Fi,Free parking,Pool,Hot tub,Air conditioning,Fitness center,Spa,3297.0
427,Little Chef Hotel,4.3,kanpur,3-star hotel,Free breakfast,Wi-Fi,Paid parking,Air conditioning,Fitness center,Bar,Restaurant,Room service,3679.0
434,Little Chef Hotel,4.3,kanpur,3-star hotel,Free breakfast,Wi-Fi,Paid parking,Air conditioning,Fitness center,Bar,Restaurant,Room service,3679.0
638,Morvee Hotels Durgapur,4.4,durgapur,Free breakfast,Free Wi-Fi,Paid parking,Spa,Restaurant,Room service,Kitchen,Airport shuttle,Full-service laundry,2245.0
647,Morvee Hotels Durgapur,4.4,durgapur,Free breakfast,Free Wi-Fi,Paid parking,Spa,Restaurant,Room service,Kitchen,Airport shuttle,Full-service laundry,2245.0
79,Sunny's World,4.2,pune,Free breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Restaurant,Kitchen,Full-service laundry,Accessible,4549.0
88,Sunny's World,4.2,pune,Free breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Restaurant,Kitchen,Full-service laundry,Accessible,4549.0
629,"The Peerless Inn, Durgapur",4.0,durgapur,3-star hotel,Free breakfast,Free Wi-Fi,Free parking,Air conditioning,Fitness center,Restaurant,Room service,Kitchen,2589.0
634,"The Peerless Inn, Durgapur",4.0,durgapur,3-star hotel,Free breakfast,Free Wi-Fi,Free parking,Air conditioning,Fitness center,Restaurant,Room service,Kitchen,2589.0
3,The Renai cochin,4.2,kochi,4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Spa,Bar,2768.0
5,The Renai cochin,4.2,kochi,4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Spa,Bar,2768.0
649,Treebo Trend Winsome Banquet And Resort,4.6,ranchi,Free breakfast,Free Wi-Fi,Paid parking,Pool,Restaurant,Room service,Kitchen,Full-service laundry,Business center,2304.0
654,Treebo Trend Winsome Banquet And Resort,4.6,ranchi,Free breakfast,Free Wi-Fi,Paid parking,Pool,Restaurant,Room service,Kitchen,Full-service laundry,Business center,2304.0

In [11]:
flight_duplicates = flights[flights.duplicated(keep=False)]
flight_duplicates.sort_values(by=flights.columns.tolist())

,airline,flightNumber,origin,destination,daysOfWeek,scheduledDepartureTime,scheduledArrivalTime,timezone,validFrom,validTo,lastUpdated
3290,Air India,588.0,Kochi,Bengaluru,"Sunday,Monday,Tuesday,Thursday,Friday,Saturday",00:15,01:15,2020-10-24,2020-03-29,2020-10-24,2025-07-16
17003,Air India,588.0,Kochi,Bengaluru,"Sunday,Monday,Tuesday,Thursday,Friday,Saturday",00:15,01:15,2020-10-24,2020-03-29,2020-10-24,2025-07-16
8600,Air India,680,Mangalore,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",07:50,09:35,2024-10-26,2024-03-31,2024-10-26,2025-07-16
19702,Air India,680,Mangalore,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",07:50,09:35,2024-10-26,2024-03-31,2024-10-26,2025-07-16
8685,Air India,680,Mangalore,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",07:55,09:35,2023-05-31,2023-03-26,2023-05-31,2025-07-16
...,...,...,...,...,...,...,...,...,...,...,...
19698,SpiceJet,4010,Mangalore,Bengaluru,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",08:10,09:25,2022-03-26,2021-10-31,2022-03-26,2025-07-16
8704,SpiceJet,4034,Mangalore,Hyderabad,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",08:45,10:50,2022-03-26,2021-10-31,2022-03-26,2025-07-16
19757,SpiceJet,4034,Mangalore,Hyderabad,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",08:45,10:50,2022-03-26,2021-10-31,2022-03-26,2025-07-16
8705,SpiceJet,8907,Mangalore,Delhi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",05:50,08:40,2020-03-28,2019-10-27,2020-03-28,2025-07-16
19758,SpiceJet,8907,Mangalore,Delhi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",05:50,08:40,2020-03-28,2019-10-27,2020-03-28,2025-07-16

In [13]:
# Hotels
hotels = hotels.drop_duplicates().reset_index(drop=True)

# Flights
flights = flights.drop_duplicates().reset_index(drop=True)

## Tousism
tourism = tourism.drop(columns=['Latitude'	,'Longitude'],axis=0)

In [14]:
print(hotels.shape)
print(flights.shape)

(1083, 13)
(33616, 11)

In [15]:
tourism.to_csv("../data/cleaned/tourism_data_clean.csv", index=False)

hotels.to_csv("../data/cleaned/hotels_data_clean.csv", index=False)

flights.to_csv("../data/cleaned/flights_clean.csv", index=False)

flight_cost.to_csv("../data/cleaned/flight_cost_clean.csv", index=False)