In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
destination_df = pd.read_csv("../data/cleaned/destination_features.csv")

destination_df.head()

,Destination,State,Category,Best_Season,Average_Budget,Recommended_Trip_Duration,Nearest_Airport,Popularity,Family_Friendly,Adventure_Score,...,Average_Hotel_Price,Minimum_Hotel_Price,Maximum_Hotel_Price,Number_of_Hotels,Average_Flight_Cost,Minimum_Flight_Cost,Maximum_Flight_Cost,Number_of_Routes,Hotel_Data_Available,Supporting_Data_Available
0,Goa,Goa,Beach,Nov-Feb,30000,4,Goa Airport,High,1,6,...,9575.500000,1157.0,26550.0,24.0,3292.592593,2200.0,4200.0,27.0,1,1
1,Ladakh (Leh),Ladakh,Mountain,Mar-Jun,35000,5,Ladakh Airport,High,1,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2,Jaipur,Rajasthan,Heritage,Oct-Mar,22000,3,Jaipur Airport,High,1,3,...,8092.913043,1039.0,34173.0,23.0,3105.555556,2200.0,6400.0,36.0,1,1
3,Varanasi (Kashi),Uttar Pradesh,Spiritual,Oct-Mar,18000,2,Varanasi Airport,High,1,2,...,3137.782609,725.0,7824.0,23.0,3013.636364,2100.0,4700.0,22.0,1,1
4,Agra,Uttar Pradesh,Heritage,Oct-Mar,22000,3,Agra Airport,High,1,3,...,NaN,NaN,NaN,NaN,3150.000000,2400.0,3600.0,8.0,0,1

In [3]:
print("Shape:", destination_df.shape)

print("\nColumns:")
print(destination_df.columns.tolist())

print("\nData Types:")
print(destination_df.dtypes)

Shape: (92, 47)

Columns:
['Destination', 'State', 'Category', 'Best_Season', 'Average_Budget', 'Recommended_Trip_Duration', 'Nearest_Airport', 'Popularity', 'Family_Friendly', 'Adventure_Score', 'Season_Mar-Jun', 'Season_Nov-Feb', 'Season_Oct-Mar', 'Category_Adventure', 'Category_Backwaters', 'Category_Beach', 'Category_Bird Sanctuary', 'Category_Coastal', 'Category_Cultural', 'Category_Desert', 'Category_Heritage', 'Category_Hill Station', 'Category_Island', 'Category_Lake', 'Category_Mountain', 'Category_Nature', 'Category_Rainforest', 'Category_Rural', 'Category_Snow', 'Category_Spiritual', 'Category_Valley', 'Category_Waterfall', 'Category_Wildlife', 'Hotel_City', 'Airport_City', 'Flight_Available', 'Average_Hotel_Rating', 'Average_Hotel_Price', 'Minimum_Hotel_Price', 'Maximum_Hotel_Price', 'Number_of_Hotels', 'Average_Flight_Cost', 'Minimum_Flight_Cost', 'Maximum_Flight_Cost', 'Number_of_Routes', 'Hotel_Data_Available', 'Supporting_Data_Available']

Data Types:
Destination                      str
State                            str
Category                         str
Best_Season                      str
Average_Budget                 int64
Recommended_Trip_Duration      int64
Nearest_Airport                  str
Popularity                       str
Family_Friendly                int64
Adventure_Score                int64
Season_Mar-Jun                 int64
Season_Nov-Feb                 int64
Season_Oct-Mar                 int64
Category_Adventure             int64
Category_Backwaters            int64
Category_Beach                 int64
Category_Bird Sanctuary        int64
Category_Coastal               int64
Category_Cultural              int64
Category_Desert                int64
Category_Heritage              int64
Category_Hill Station          int64
Category_Island                int64
Category_Lake                  int64
Category_Mountain              int64
Category_Nature                int64
Category_Rainforest            int64
Category_Rural                 int64
Category_Snow                  int64
Category_Spiritual             int64
Category_Valley                int64
Category_Waterfall             int64
Category_Wildlife              int64
Hotel_City                       str
Airport_City                     str
Flight_Available               int64
Average_Hotel_Rating         float64
Average_Hotel_Price          float64
Minimum_Hotel_Price          float64
Maximum_Hotel_Price          float64
Number_of_Hotels             float64
Average_Flight_Cost          float64
Minimum_Flight_Cost          float64
Maximum_Flight_Cost          float64
Number_of_Routes             float64
Hotel_Data_Available           int64
Supporting_Data_Available      int64
dtype: object

In [4]:
destination_df.isnull().sum()

Destination                   0
State                         0
Category                      0
Best_Season                   0
Average_Budget                0
Recommended_Trip_Duration     0
Nearest_Airport               0
Popularity                    0
Family_Friendly               0
Adventure_Score               0
Season_Mar-Jun                0
Season_Nov-Feb                0
Season_Oct-Mar                0
Category_Adventure            0
Category_Backwaters           0
Category_Beach                0
Category_Bird Sanctuary       0
Category_Coastal              0
Category_Cultural             0
Category_Desert               0
Category_Heritage             0
Category_Hill Station         0
Category_Island               0
Category_Lake                 0
Category_Mountain             0
Category_Nature               0
Category_Rainforest           0
Category_Rural                0
Category_Snow                 0
Category_Spiritual            0
Category_Valley               0
Category_Waterfall            0
Category_Wildlife             0
Hotel_City                   83
Airport_City                  0
Flight_Available              0
Average_Hotel_Rating         83
Average_Hotel_Price          83
Minimum_Hotel_Price          83
Maximum_Hotel_Price          83
Number_of_Hotels             83
Average_Flight_Cost          81
Minimum_Flight_Cost          81
Maximum_Flight_Cost          81
Number_of_Routes             81
Hotel_Data_Available          0
Supporting_Data_Available     0
dtype: int64

In [5]:
print("Duplicate rows:", destination_df.duplicated().sum())

Duplicate rows: 0

In [6]:
# These columns contain categorical information.
# Before converting them into numerical features,
# we first need to understand what values they contain.

categorical_columns = [
    "Category",
    "Best_Season",
    "Popularity",
    "State"
]

# Display the unique value counts for each categorical column.
# This helps us decide how each column should be encoded.
for column in categorical_columns:
    print(f"\n{column}:")
    print(destination_df[column].value_counts())

Category:
Category
Hill Station      16
Spiritual         10
Heritage           9
Nature             8
Island             7
Beach              6
Wildlife           6
Mountain           5
Adventure          5
Coastal            3
Desert             3
Bird Sanctuary     3
Valley             2
Waterfall          2
Snow               2
Backwaters         1
Lake               1
Cultural           1
Rainforest         1
Rural              1
Name: count, dtype: int64

Best_Season:
Best_Season
Oct-Mar    46
Mar-Jun    30
Nov-Feb    16
Name: count, dtype: int64

Popularity:
Popularity
High    92
Name: count, dtype: int64

State:
State
Uttarakhand              10
Karnataka                 9
Himachal Pradesh          8
Meghalaya                 6
Tamil Nadu                6
Rajasthan                 5
Kerala                    5
Madhya Pradesh            5
Gujarat                   4
Maharashtra               4
Ladakh                    3
Uttar Pradesh             3
Andaman & Nicobar         3
Lakshadweep               3
Goa                       2
Arunachal Pradesh         2
Assam                     2
Sikkim                    2
Chhattisgarh              1
Puducherry                1
Andhra Pradesh            1
Punjab                    1
West Bengal               1
Odisha                    1
Tripura                   1
Uttar Pradesh/Gujarat     1
Bihar                     1
Jammu & Kashmir           1
Name: count, dtype: int64

In [7]:
# These are the important numerical features that may be
# useful for the destination recommendation system.
#
# We use describe() to understand their:
# - count
# - mean
# - minimum
# - maximum
# - standard deviation

numerical_columns = [
    "Average_Budget",
    "Recommended_Trip_Duration",
    "Family_Friendly",
    "Adventure_Score",
    "Average_Hotel_Rating",
    "Average_Hotel_Price",
    "Average_Flight_Cost"
]

# Generate statistical summary for the selected features.
destination_df[numerical_columns].describe()

,Average_Budget,Recommended_Trip_Duration,Family_Friendly,Adventure_Score,Average_Hotel_Rating,Average_Hotel_Price,Average_Flight_Cost
count,92.000000,92.000000,92.0,92.000000,9.000000,9.000000,11.000000
mean,28043.478261,3.717391,1.0,6.369565,4.220428,4902.917320,3778.023514
std,5862.739568,1.041196,0.0,2.421140,0.132443,2832.990586,1378.163602
min,18000.000000,2.000000,1.0,2.000000,4.063636,2043.772727,2700.000000
25%,25000.000000,3.000000,1.0,5.000000,4.086957,3034.636364,3059.595960
50%,27500.000000,3.500000,1.0,7.000000,4.291304,3137.782609,3292.592593
75%,35000.000000,5.000000,1.0,9.000000,4.309524,8048.130435,3543.421053
max,35000.000000,5.000000,1.0,9.000000,4.391304,9575.500000,6628.571429

In [8]:
# These are the numerical and encoded features that describe
# a destination's characteristics.
#
# We will use these features to compare destinations based
# on a user's travel preferences.

recommendation_features = [
    "Average_Budget",
    "Recommended_Trip_Duration",
    "Adventure_Score",

    # Season features
    "Season_Mar-Jun",
    "Season_Nov-Feb",
    "Season_Oct-Mar",

    # Category features
    "Category_Adventure",
    "Category_Backwaters",
    "Category_Beach",
    "Category_Bird Sanctuary",
    "Category_Coastal",
    "Category_Cultural",
    "Category_Desert",
    "Category_Heritage",
    "Category_Hill Station",
    "Category_Island",
    "Category_Lake",
    "Category_Mountain",
    "Category_Nature",
    "Category_Rainforest",
    "Category_Rural",
    "Category_Snow",
    "Category_Spiritual",
    "Category_Valley",
    "Category_Waterfall",
    "Category_Wildlife"
]

# Create a separate DataFrame containing only
# the features required by our recommendation system.
X_recommendation = destination_df[recommendation_features].copy()

# Display the first few rows to verify the selected features.
X_recommendation.head()

,Average_Budget,Recommended_Trip_Duration,Adventure_Score,Season_Mar-Jun,Season_Nov-Feb,Season_Oct-Mar,Category_Adventure,Category_Backwaters,Category_Beach,Category_Bird Sanctuary,...,Category_Lake,Category_Mountain,Category_Nature,Category_Rainforest,Category_Rural,Category_Snow,Category_Spiritual,Category_Valley,Category_Waterfall,Category_Wildlife
0,30000,4,6,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,35000,5,9,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,22000,3,3,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,18000,2,2,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,22000,3,3,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
# Check the shape of our final recommendation feature matrix.
# 92 rows = 92 destinations
# Number of columns = number of features used by the model.

print("Recommendation feature matrix shape:", X_recommendation.shape)

# Check whether any missing values exist in these features.
print("\nMissing values:")
print(X_recommendation.isnull().sum().sum())

Recommendation feature matrix shape: (92, 26)

Missing values:
0

### Average_Budget            → 18,000 to 35,000
### Recommended_Trip_Duration → 2 to 5
### Adventure_Score           → 2 to 9

In [10]:
## Import standard scaler
# StandardScaler converts numerical features to a common scale.
# This is important because our recommendation system
# will compare destinations based on feature similarity.

from sklearn.preprocessing import StandardScaler

In [11]:
# Create the scaler object.
scaler = StandardScaler()

# Fit the scaler on our recommendation features
# and transform the data into a standardized form.
X_scaled = scaler.fit_transform(X_recommendation)

# Convert the scaled NumPy array back into a DataFrame
# so that we can easily inspect and work with the features.
X_scaled = pd.DataFrame(
    X_scaled,
    columns=recommendation_features
)

# Display the first five rows of the scaled features.
X_scaled.head()

,Average_Budget,Recommended_Trip_Duration,Adventure_Score,Season_Mar-Jun,Season_Nov-Feb,Season_Oct-Mar,Category_Adventure,Category_Backwaters,Category_Beach,Category_Bird Sanctuary,...,Category_Lake,Category_Mountain,Category_Nature,Category_Rainforest,Category_Rural,Category_Snow,Category_Spiritual,Category_Valley,Category_Waterfall,Category_Wildlife
0,0.335550,0.272914,-0.153477,-0.695608,2.179449,-1.0,-0.239732,-0.104828,3.785939,-0.183597,...,-0.104828,-0.239732,-0.308607,-0.104828,-0.104828,-0.149071,-0.349215,-0.149071,-0.149071,-0.264135
1,1.193067,1.238611,1.092398,1.437591,-0.458831,-1.0,-0.239732,-0.104828,-0.264135,-0.183597,...,-0.104828,4.171331,-0.308607,-0.104828,-0.104828,-0.149071,-0.349215,-0.149071,-0.149071,-0.264135
2,-1.036477,-0.692782,-1.399352,-0.695608,-0.458831,1.0,-0.239732,-0.104828,-0.264135,-0.183597,...,-0.104828,-0.239732,-0.308607,-0.104828,-0.104828,-0.149071,-0.349215,-0.149071,-0.149071,-0.264135
3,-1.722490,-1.658478,-1.814644,-0.695608,-0.458831,1.0,-0.239732,-0.104828,-0.264135,-0.183597,...,-0.104828,-0.239732,-0.308607,-0.104828,-0.104828,-0.149071,2.863564,-0.149071,-0.149071,-0.264135
4,-1.036477,-0.692782,-1.399352,-0.695608,-0.458831,1.0,-0.239732,-0.104828,-0.264135,-0.183597,...,-0.104828,-0.239732,-0.308607,-0.104828,-0.104828,-0.149071,-0.349215,-0.149071,-0.149071,-0.264135

In [12]:
# Check the mean and standard deviation after scaling.
# StandardScaler should make the mean approximately 0
# and the standard deviation approximately 1.

print("Mean of scaled features:")
print(X_scaled.mean().round(2))

print("\nStandard deviation of scaled features:")
print(X_scaled.std().round(2))

Mean of scaled features:
Average_Budget               0.0
Recommended_Trip_Duration   -0.0
Adventure_Score             -0.0
Season_Mar-Jun               0.0
Season_Nov-Feb               0.0
Season_Oct-Mar               0.0
Category_Adventure           0.0
Category_Backwaters          0.0
Category_Beach               0.0
Category_Bird Sanctuary      0.0
Category_Coastal            -0.0
Category_Cultural           -0.0
Category_Desert             -0.0
Category_Heritage            0.0
Category_Hill Station        0.0
Category_Island             -0.0
Category_Lake                0.0
Category_Mountain           -0.0
Category_Nature              0.0
Category_Rainforest         -0.0
Category_Rural              -0.0
Category_Snow                0.0
Category_Spiritual           0.0
Category_Valley             -0.0
Category_Waterfall          -0.0
Category_Wildlife            0.0
dtype: float64

Standard deviation of scaled features:
Average_Budget               1.01
Recommended_Trip_Duration    1.01
Adventure_Score              1.01
Season_Mar-Jun               1.01
Season_Nov-Feb               1.01
Season_Oct-Mar               1.01
Category_Adventure           1.01
Category_Backwaters          1.01
Category_Beach               1.01
Category_Bird Sanctuary      1.01
Category_Coastal             1.01
Category_Cultural            1.01
Category_Desert              1.01
Category_Heritage            1.01
Category_Hill Station        1.01
Category_Island              1.01
Category_Lake                1.01
Category_Mountain            1.01
Category_Nature              1.01
Category_Rainforest          1.01
Category_Rural               1.01
Category_Snow                1.01
Category_Spiritual           1.01
Category_Valley              1.01
Category_Waterfall           1.01
Category_Wildlife            1.01
dtype: float64

In [13]:
# Create a copy of the destination names.
# We need these later to identify which destination
# each feature vector belongs to.
destination_info = destination_df[
    ["Destination", "State", "Category", "Best_Season"]
].copy()

# Reset the index so that it matches the scaled feature DataFrame.
destination_info = destination_info.reset_index(drop=True)

# Reset the index of the scaled features as well.
X_scaled = X_scaled.reset_index(drop=True)

# Combine destination information with the scaled ML features.
# axis=1 means we are joining them column-wise.
recommendation_data = pd.concat(
    [destination_info, X_scaled],
    axis=1
)

# Display the first five rows.
recommendation_data.head()

,Destination,State,Category,Best_Season,Average_Budget,Recommended_Trip_Duration,Adventure_Score,Season_Mar-Jun,Season_Nov-Feb,Season_Oct-Mar,...,Category_Lake,Category_Mountain,Category_Nature,Category_Rainforest,Category_Rural,Category_Snow,Category_Spiritual,Category_Valley,Category_Waterfall,Category_Wildlife
0,Goa,Goa,Beach,Nov-Feb,0.335550,0.272914,-0.153477,-0.695608,2.179449,-1.0,...,-0.104828,-0.239732,-0.308607,-0.104828,-0.104828,-0.149071,-0.349215,-0.149071,-0.149071,-0.264135
1,Ladakh (Leh),Ladakh,Mountain,Mar-Jun,1.193067,1.238611,1.092398,1.437591,-0.458831,-1.0,...,-0.104828,4.171331,-0.308607,-0.104828,-0.104828,-0.149071,-0.349215,-0.149071,-0.149071,-0.264135
2,Jaipur,Rajasthan,Heritage,Oct-Mar,-1.036477,-0.692782,-1.399352,-0.695608,-0.458831,1.0,...,-0.104828,-0.239732,-0.308607,-0.104828,-0.104828,-0.149071,-0.349215,-0.149071,-0.149071,-0.264135
3,Varanasi (Kashi),Uttar Pradesh,Spiritual,Oct-Mar,-1.722490,-1.658478,-1.814644,-0.695608,-0.458831,1.0,...,-0.104828,-0.239732,-0.308607,-0.104828,-0.104828,-0.149071,2.863564,-0.149071,-0.149071,-0.264135
4,Agra,Uttar Pradesh,Heritage,Oct-Mar,-1.036477,-0.692782,-1.399352,-0.695608,-0.458831,1.0,...,-0.104828,-0.239732,-0.308607,-0.104828,-0.104828,-0.149071,-0.349215,-0.149071,-0.149071,-0.264135

In [14]:
# Check the shape of our final recommendation dataset.
print("Final recommendation dataset shape:", recommendation_data.shape)

# Check the first few destination names.
print("\nDestinations:")
print(recommendation_data["Destination"].head())

# Check whether any missing values were introduced.
print("\nTotal missing values:")
print(recommendation_data.isnull().sum().sum())

Final recommendation dataset shape: (92, 30)

Destinations:
0                 Goa
1        Ladakh (Leh)
2              Jaipur
3    Varanasi (Kashi)
4                Agra
Name: Destination, dtype: str

Total missing values:
0

In [15]:
# Cosine similarity measures how similar two feature vectors are.
# We will use it to compare the user's travel preferences
# with every destination in our dataset.

from sklearn.metrics.pairwise import cosine_similarity

In [16]:
def calculate_similarity(user_vector, destination_matrix):
    """
    Calculate how similar the user's preferences are
    to every destination in the dataset.

    Parameters:
        user_vector: User's feature vector
        destination_matrix: Scaled destination features

    Returns:
        Similarity score for every destination
    """

    # Calculate cosine similarity between the user's
    # preference vector and all destination feature vectors.
    similarity_scores = cosine_similarity(
        user_vector,
        destination_matrix
    )

    # Convert the result into a one-dimensional array.
    return similarity_scores[0]

In [17]:
# Take the first destination's scaled feature vector
# and use it as a temporary test user vector.
test_user_vector = X_scaled.iloc[[0]].values

# Calculate similarity between this test vector
# and all 92 destinations.
test_scores = calculate_similarity(
    test_user_vector,
    X_scaled.values
)

# Display the first 10 similarity scores.
print(test_scores[:10])

[ 1.         -0.06151224 -0.1593058  -0.16159452 -0.1593058  -0.1593058
 -0.06108727 -0.09562606 -0.04173859 -0.17102895]

In [18]:
# Define a sample user's travel preferences.
# These values will later come from the actual user interface.

user_budget = 25000
user_duration = 4
user_season = "Nov-Feb"
user_category = "Adventure"

In [19]:
# Create a dictionary containing all recommendation features.
# Initially, every feature is set to 0.
#
# We will then replace the relevant features with
# the user's actual preferences.

user_features = {
    feature: 0
    for feature in recommendation_features
}

# Set the user's numerical preferences.
user_features["Average_Budget"] = user_budget
user_features["Recommended_Trip_Duration"] = user_duration

# Set the user's preferred season.
# The corresponding season feature is changed to 1.
user_features[f"Season_{user_season}"] = 1

# Set the user's preferred category.
# The corresponding category feature is changed to 1.
user_features[f"Category_{user_category}"] = 1

# Convert the dictionary into a DataFrame.
# The double brackets keep it as a single-row DataFrame.
user_df = pd.DataFrame([user_features])

# Display the user feature vector.
user_df

,Average_Budget,Recommended_Trip_Duration,Adventure_Score,Season_Mar-Jun,Season_Nov-Feb,Season_Oct-Mar,Category_Adventure,Category_Backwaters,Category_Beach,Category_Bird Sanctuary,...,Category_Lake,Category_Mountain,Category_Nature,Category_Rainforest,Category_Rural,Category_Snow,Category_Spiritual,Category_Valley,Category_Waterfall,Category_Wildlife
0,25000,4,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
# Transform the user's feature vector using the SAME scaler
# that was fitted on the destination features.
#
# We use transform(), not fit_transform(), because we don't
# want to create a new scaling system for the user.

user_scaled = scaler.transform(user_df)

# Display the scaled user vector.
user_scaled

array([[-0.52196673,  0.27291418, -2.64522755, -0.69560834,  2.17944947,
        -1.        ,  4.17133072, -0.10482848, -0.26413527, -0.18359702,
        -0.18359702, -0.10482848, -0.18359702, -0.32929278, -0.45883147,
        -0.28697202, -0.10482848, -0.23973165, -0.3086067 , -0.10482848,
        -0.10482848, -0.1490712 , -0.34921515, -0.1490712 , -0.1490712 ,
        -0.26413527]])

In [21]:
# Calculate cosine similarity between the user's preferences
# and all 92 destination feature vectors.

user_similarity_scores = calculate_similarity(
    user_scaled,
    X_scaled.values
)

# Add the similarity scores to our recommendation dataset.
# We create a copy so the original dataset remains unchanged.

recommendation_results = recommendation_data.copy()

recommendation_results["Similarity_Score"] = user_similarity_scores

# Sort destinations from highest similarity to lowest similarity.
recommendation_results = recommendation_results.sort_values(
    by="Similarity_Score",
    ascending=False
)

# Display the top 10 recommended destinations.
recommendation_results[
    ["Destination", "State", "Category", "Best_Season", "Similarity_Score"]
].head(10)

,Destination,State,Category,Best_Season,Similarity_Score
16,Nubra Valley,Ladakh,Adventure,Mar-Jun,0.495662
15,Spiti Valley,Himachal Pradesh,Adventure,Mar-Jun,0.495662
61,North Sikkim,Sikkim,Adventure,Mar-Jun,0.495662
36,Rishikesh,Uttarakhand,Adventure,Mar-Jun,0.495662
69,Miyar Valley,Himachal Pradesh,Adventure,Mar-Jun,0.495662
47,Lakshadweep Circuit,Lakshadweep,Island,Nov-Feb,0.219358
58,Port Blair,Andaman & Nicobar,Island,Nov-Feb,0.219358
48,Kalpeni Island,Lakshadweep,Island,Nov-Feb,0.219358
31,Neil Island,Andaman & Nicobar,Island,Nov-Feb,0.219358
30,Havelock Island,Andaman & Nicobar,Island,Nov-Feb,0.219358

In [22]:
# Display the important destination features for the current
# top recommendations.
#
# This helps us understand why the similarity calculation
# ranked these destinations so highly.

top_destinations = recommendation_results.head(10)["Destination"]

destination_df[
    destination_df["Destination"].isin(top_destinations)
][
    [
        "Destination",
        "Average_Budget",
        "Recommended_Trip_Duration",
        "Adventure_Score",
        "Best_Season",
        "Category"
    ]
].sort_values("Destination")

,Destination,Average_Budget,Recommended_Trip_Duration,Adventure_Score,Best_Season,Category
30,Havelock Island,30000,4,6,Nov-Feb,Island
48,Kalpeni Island,30000,4,6,Nov-Feb,Island
47,Lakshadweep Circuit,30000,4,6,Nov-Feb,Island
69,Miyar Valley,35000,5,9,Mar-Jun,Adventure
31,Neil Island,30000,4,6,Nov-Feb,Island
61,North Sikkim,35000,5,9,Mar-Jun,Adventure
16,Nubra Valley,35000,5,9,Mar-Jun,Adventure
58,Port Blair,30000,4,6,Nov-Feb,Island
36,Rishikesh,35000,5,9,Mar-Jun,Adventure
15,Spiti Valley,35000,5,9,Mar-Jun,Adventure

In [23]:
# Check how many destinations match the user's preferred
# season AND preferred category exactly.
#
# Our current user preferences are:
# Season  = Nov-Feb
# Category = Adventure

exact_matches = destination_df[
    (destination_df["Best_Season"] == user_season) &
    (destination_df["Category"] == user_category)
]

# Display the number of exact matches.
print("Exact season + category matches:", len(exact_matches))

# Display the matching destinations, if any exist.
exact_matches[
    [
        "Destination",
        "Average_Budget",
        "Recommended_Trip_Duration",
        "Adventure_Score",
        "Best_Season",
        "Category"
    ]
]

Exact season + category matches: 0

Empty DataFrame
Columns: [Destination, Average_Budget, Recommended_Trip_Duration, Adventure_Score, Best_Season, Category]
Index: []

In [24]:
# Filter all destinations that are suitable for the
# user's selected travel season.

season_matches = destination_df[
    destination_df["Best_Season"] == user_season
]

# Display the available destinations for this season.
season_matches[
    [
        "Destination",
        "Average_Budget",
        "Recommended_Trip_Duration",
        "Adventure_Score",
        "Best_Season",
        "Category"
    ]
].sort_values("Average_Budget")

,Destination,Average_Budget,Recommended_Trip_Duration,Adventure_Score,Best_Season,Category
0,Goa,30000,4,6,Nov-Feb,Beach
20,Kanyakumari,30000,4,6,Nov-Feb,Coastal
22,Dhanushkodi,30000,4,6,Nov-Feb,Coastal
24,Gokarna,30000,4,6,Nov-Feb,Beach
25,Pondicherry,30000,4,6,Nov-Feb,Coastal
27,Majuli Island,30000,4,6,Nov-Feb,Island
29,Varkala,30000,4,6,Nov-Feb,Beach
30,Havelock Island,30000,4,6,Nov-Feb,Island
31,Neil Island,30000,4,6,Nov-Feb,Island
47,Lakshadweep Circuit,30000,4,6,Nov-Feb,Island
48,Kalpeni Island,30000,4,6,Nov-Feb,Island
58,Port Blair,30000,4,6,Nov-Feb,Island
74,Maravanthe,30000,4,6,Nov-Feb,Beach
75,Astaranga & Ramachandi,30000,4,6,Nov-Feb,Beach
78,Hidden Goa Coves,30000,4,6,Nov-Feb,Beach
79,Bangaram & Kadmat,30000,4,6,Nov-Feb,Island

In [25]:
# Calculate how closely each destination's budget matches
# the user's requested budget.
#
# A score of 1 means the destination exactly matches
# the user's budget.
#
# As the difference increases, the score decreases.

budget_difference = (
    destination_df["Average_Budget"] - user_budget
).abs()

budget_score = 1 - (
    budget_difference / destination_df["Average_Budget"].max()
)

# Keep the score between 0 and 1.
budget_score = budget_score.clip(0, 1)

# Display the first few scores.
budget_score.head()

0    0.857143
1    0.714286
2    0.914286
3    0.800000
4    0.914286
Name: Average_Budget, dtype: float64

In [26]:
# Calculate how closely each destination's recommended
# trip duration matches the user's requested duration.
#
# A score of 1 means the duration matches exactly.

duration_difference = (
    destination_df["Recommended_Trip_Duration"] - user_duration
).abs()

duration_score = 1 - (
    duration_difference /
    destination_df["Recommended_Trip_Duration"].max()
)

# Keep the score between 0 and 1.
duration_score = duration_score.clip(0, 1)

# Display the first few scores.
duration_score.head()

0    1.0
1    0.8
2    0.8
3    0.6
4    0.8
Name: Recommended_Trip_Duration, dtype: float64

In [27]:
# Give a binary score for the user's preferred season.
#
# 1 = destination's best season matches the user's season
# 0 = destination's best season does not match

season_score = (
    destination_df["Best_Season"] == user_season
).astype(int)

# Display the season matching scores.
season_score.head()

0    1
1    0
2    0
3    0
4    0
Name: Best_Season, dtype: int64

In [35]:
# Give a binary score for the user's preferred category.
#
# 1 = destination belongs to the preferred category
# 0 = destination belongs to another category

category_score = (
    destination_df["Category"] == user_category
).astype(int)

# Display the category matching scores.
category_score.head()

0    0
1    0
2    0
3    0
4    0
Name: Category, dtype: int64

In [36]:
# Display all destinations that match the user's
# preferred category.

category_matches = destination_df[
    destination_df["Category"] == user_category
][
    ["Destination", "Category"]
]

# Show the matching destinations.
category_matches

     Destination   Category
15  Spiti Valley  Adventure
16  Nubra Valley  Adventure
36     Rishikesh  Adventure
61  North Sikkim  Adventure
69  Miyar Valley  Adventure

In [32]:
# Normalize the Adventure_Score to a 0-1 range.
#
# This allows us to combine it with our other scores,
# which are also between 0 and 1.

adventure_score = (
    destination_df["Adventure_Score"] -
    destination_df["Adventure_Score"].min()
) / (
    destination_df["Adventure_Score"].max() -
    destination_df["Adventure_Score"].min()
)

# Display the normalized adventure scores.
adventure_score.head()

0    0.571429
1    1.000000
2    0.142857
3    0.000000
4    0.142857
Name: Adventure_Score, dtype: float64

In [37]:
# Define the importance of each recommendation component.
# The weights add up to 1.0 (100%).

SEASON_WEIGHT = 0.30
CATEGORY_WEIGHT = 0.30
BUDGET_WEIGHT = 0.20
DURATION_WEIGHT = 0.10
ADVENTURE_WEIGHT = 0.10


# Calculate the final recommendation score.
#
# Each individual score is between 0 and 1.
# The weighted sum therefore also produces a score
# between 0 and 1.

recommendation_score = (
    season_score * SEASON_WEIGHT
    + category_score * CATEGORY_WEIGHT
    + budget_score * BUDGET_WEIGHT
    + duration_score * DURATION_WEIGHT
    + adventure_score * ADVENTURE_WEIGHT
)


# Create a copy of the destination information
# so we can attach the individual scores and final score.

scored_destinations = destination_df[
    [
        "Destination",
        "State",
        "Category",
        "Best_Season",
        "Average_Budget",
        "Recommended_Trip_Duration",
        "Adventure_Score"
    ]
].copy()


# Add each individual scoring component.
scored_destinations["Season_Score"] = season_score
scored_destinations["Category_Score"] = category_score
scored_destinations["Budget_Score"] = budget_score
scored_destinations["Duration_Score"] = duration_score
scored_destinations["Adventure_Score_Normalized"] = adventure_score


# Add the final weighted recommendation score.
scored_destinations["Recommendation_Score"] = recommendation_score


# Sort destinations from highest recommendation score
# to lowest recommendation score.

scored_destinations = scored_destinations.sort_values(
    by="Recommendation_Score",
    ascending=False
)


# Display the top 10 recommendations.
scored_destinations.head(10)

,Destination,State,Category,Best_Season,Average_Budget,Recommended_Trip_Duration,Adventure_Score,Season_Score,Category_Score,Budget_Score,Duration_Score,Adventure_Score_Normalized,Recommendation_Score
0,Goa,Goa,Beach,Nov-Feb,30000,4,6,1,0,0.857143,1.0,0.571429,0.628571
22,Dhanushkodi,Tamil Nadu,Coastal,Nov-Feb,30000,4,6,1,0,0.857143,1.0,0.571429,0.628571
25,Pondicherry,Puducherry,Coastal,Nov-Feb,30000,4,6,1,0,0.857143,1.0,0.571429,0.628571
24,Gokarna,Karnataka,Beach,Nov-Feb,30000,4,6,1,0,0.857143,1.0,0.571429,0.628571
27,Majuli Island,Assam,Island,Nov-Feb,30000,4,6,1,0,0.857143,1.0,0.571429,0.628571
20,Kanyakumari,Tamil Nadu,Coastal,Nov-Feb,30000,4,6,1,0,0.857143,1.0,0.571429,0.628571
58,Port Blair,Andaman & Nicobar,Island,Nov-Feb,30000,4,6,1,0,0.857143,1.0,0.571429,0.628571
48,Kalpeni Island,Lakshadweep,Island,Nov-Feb,30000,4,6,1,0,0.857143,1.0,0.571429,0.628571
47,Lakshadweep Circuit,Lakshadweep,Island,Nov-Feb,30000,4,6,1,0,0.857143,1.0,0.571429,0.628571
31,Neil Island,Andaman & Nicobar,Island,Nov-Feb,30000,4,6,1,0,0.857143,1.0,0.571429,0.628571

In [38]:
# Select only the important columns needed to understand
# the final recommendations.

top_recommendations = scored_destinations[
    [
        "Destination",
        "State",
        "Category",
        "Best_Season",
        "Average_Budget",
        "Recommended_Trip_Duration",
        "Adventure_Score",
        "Recommendation_Score"
    ]
].head(10)


# Round the recommendation score to make the output
# easier to read.

top_recommendations["Recommendation_Score"] = (
    top_recommendations["Recommendation_Score"].round(3)
)


# Display the top 10 recommendations.

top_recommendations

,Destination,State,Category,Best_Season,Average_Budget,Recommended_Trip_Duration,Adventure_Score,Recommendation_Score
0,Goa,Goa,Beach,Nov-Feb,30000,4,6,0.629
22,Dhanushkodi,Tamil Nadu,Coastal,Nov-Feb,30000,4,6,0.629
25,Pondicherry,Puducherry,Coastal,Nov-Feb,30000,4,6,0.629
24,Gokarna,Karnataka,Beach,Nov-Feb,30000,4,6,0.629
27,Majuli Island,Assam,Island,Nov-Feb,30000,4,6,0.629
20,Kanyakumari,Tamil Nadu,Coastal,Nov-Feb,30000,4,6,0.629
58,Port Blair,Andaman & Nicobar,Island,Nov-Feb,30000,4,6,0.629
48,Kalpeni Island,Lakshadweep,Island,Nov-Feb,30000,4,6,0.629
47,Lakshadweep Circuit,Lakshadweep,Island,Nov-Feb,30000,4,6,0.629
31,Neil Island,Andaman & Nicobar,Island,Nov-Feb,30000,4,6,0.629

In [39]:
# Select the important columns that we want to see
# when reviewing the final recommendations.

top_recommendations = scored_destinations[
    [
        "Destination",
        "State",
        "Category",
        "Best_Season",
        "Average_Budget",
        "Recommended_Trip_Duration",
        "Adventure_Score",
        "Season_Score",
        "Category_Score",
        "Budget_Score",
        "Duration_Score",
        "Recommendation_Score"
    ]
].head(10)


# Round the score columns to make the output
# easier to read and understand.

score_columns = [
    "Season_Score",
    "Category_Score",
    "Budget_Score",
    "Duration_Score",
    "Recommendation_Score"
]

top_recommendations[score_columns] = (
    top_recommendations[score_columns].round(3)
)


# Display the top 10 destinations.
top_recommendations

,Destination,State,Category,Best_Season,Average_Budget,Recommended_Trip_Duration,Adventure_Score,Season_Score,Category_Score,Budget_Score,Duration_Score,Recommendation_Score
0,Goa,Goa,Beach,Nov-Feb,30000,4,6,1,0,0.857,1.0,0.629
22,Dhanushkodi,Tamil Nadu,Coastal,Nov-Feb,30000,4,6,1,0,0.857,1.0,0.629
25,Pondicherry,Puducherry,Coastal,Nov-Feb,30000,4,6,1,0,0.857,1.0,0.629
24,Gokarna,Karnataka,Beach,Nov-Feb,30000,4,6,1,0,0.857,1.0,0.629
27,Majuli Island,Assam,Island,Nov-Feb,30000,4,6,1,0,0.857,1.0,0.629
20,Kanyakumari,Tamil Nadu,Coastal,Nov-Feb,30000,4,6,1,0,0.857,1.0,0.629
58,Port Blair,Andaman & Nicobar,Island,Nov-Feb,30000,4,6,1,0,0.857,1.0,0.629
48,Kalpeni Island,Lakshadweep,Island,Nov-Feb,30000,4,6,1,0,0.857,1.0,0.629
47,Lakshadweep Circuit,Lakshadweep,Island,Nov-Feb,30000,4,6,1,0,0.857,1.0,0.629
31,Neil Island,Andaman & Nicobar,Island,Nov-Feb,30000,4,6,1,0,0.857,1.0,0.629

In [40]:
# Get the highest-ranked destination from our recommendation results.

best_destination = scored_destinations.iloc[0]

# Display the most important information about
# the recommended destination.

print("Best Recommendation")
print("--------------------")
print("Destination:", best_destination["Destination"])
print("State:", best_destination["State"])
print("Category:", best_destination["Category"])
print("Best Season:", best_destination["Best_Season"])
print("Average Budget:", best_destination["Average_Budget"])
print("Trip Duration:", best_destination["Recommended_Trip_Duration"])
print("Adventure Score:", best_destination["Adventure_Score"])
print("Recommendation Score:", round(
    best_destination["Recommendation_Score"], 3
))

Best Recommendation
--------------------
Destination: Goa
State: Goa
Category: Beach
Best Season: Nov-Feb
Average Budget: 30000
Trip Duration: 4
Adventure Score: 6
Recommendation Score: 0.629

In [41]:
# Get the destinations that currently have the highest
# recommendation score.

highest_score = scored_destinations["Recommendation_Score"].max()

tied_destinations = scored_destinations[
    scored_destinations["Recommendation_Score"] == highest_score
]

# Check whether these destinations have differences
# in their supporting travel data.

tied_destinations[
    [
        "Destination",
        "State",
        "Category",
        "Best_Season"
    ]
]

               Destination              State Category Best_Season
0                      Goa                Goa    Beach     Nov-Feb
22             Dhanushkodi         Tamil Nadu  Coastal     Nov-Feb
25             Pondicherry         Puducherry  Coastal     Nov-Feb
24                 Gokarna          Karnataka    Beach     Nov-Feb
27           Majuli Island              Assam   Island     Nov-Feb
20             Kanyakumari         Tamil Nadu  Coastal     Nov-Feb
58              Port Blair  Andaman & Nicobar   Island     Nov-Feb
48          Kalpeni Island        Lakshadweep   Island     Nov-Feb
47     Lakshadweep Circuit        Lakshadweep   Island     Nov-Feb
31             Neil Island  Andaman & Nicobar   Island     Nov-Feb
30         Havelock Island  Andaman & Nicobar   Island     Nov-Feb
29                 Varkala             Kerala    Beach     Nov-Feb
75  Astaranga & Ramachandi             Odisha    Beach     Nov-Feb
74              Maravanthe          Karnataka    Beach     Nov-Feb
78        Hidden Goa Coves                Goa    Beach     Nov-Feb
79       Bangaram & Kadmat        Lakshadweep   Island     Nov-Feb

In [42]:
# Select useful supporting features that may help
# distinguish destinations with identical recommendation scores.

tie_breaker_features = destination_df[
    destination_df["Destination"].isin(
        tied_destinations["Destination"]
    )
][
    [
        "Destination",
        "Flight_Available",
        "Hotel_Data_Available",
        "Supporting_Data_Available",
        "Number_of_Hotels",
        "Number_of_Routes",
        "Average_Hotel_Rating",
        "Average_Flight_Cost"
    ]
]

# Display the available tie-breaking information.
tie_breaker_features

,Destination,Flight_Available,Hotel_Data_Available,Supporting_Data_Available,Number_of_Hotels,Number_of_Routes,Average_Hotel_Rating,Average_Flight_Cost
0,Goa,1,1,1,24.0,27.0,4.345833,3292.592593
20,Kanyakumari,0,1,1,22.0,NaN,4.100000,NaN
22,Dhanushkodi,0,0,0,NaN,NaN,NaN,NaN
24,Gokarna,0,0,0,NaN,NaN,NaN,NaN
25,Pondicherry,1,1,1,22.0,2.0,4.063636,3550.000000
27,Majuli Island,0,0,0,NaN,NaN,NaN,NaN
29,Varkala,0,1,1,21.0,NaN,4.309524,NaN
30,Havelock Island,0,0,0,NaN,NaN,NaN,NaN
31,Neil Island,0,0,0,NaN,NaN,NaN,NaN
47,Lakshadweep Circuit,0,0,0,NaN,NaN,NaN,NaN
48,Kalpeni Island,0,0,0,NaN,NaN,NaN,NaN
58,Port Blair,1,0,1,NaN,7.0,NaN,6628.571429
74,Maravanthe,0,0,0,NaN,NaN,NaN,NaN
75,Astaranga & Ramachandi,0,0,0,NaN,NaN,NaN,NaN
78,Hidden Goa Coves,0,0,0,NaN,NaN,NaN,NaN
79,Bangaram & Kadmat,0,0,0,NaN,NaN,NaN,NaN

Recommendation function

In [43]:
def recommend_destinations(
    budget,
    duration,
    season,
    category,
    top_n=5
):
    """
    Recommend travel destinations based on user preferences.

    Parameters:
        budget   : User's maximum/preferred travel budget.
        duration : Preferred number of travel days.
        season   : Preferred travel season.
        category : Preferred destination category.
        top_n    : Number of recommendations to return.

    Returns:
        A DataFrame containing the top recommended destinations.
    """

    # ---------------------------------------------------------
    # 1. Calculate budget similarity
    # ---------------------------------------------------------
    # A destination closer to the user's budget
    # receives a higher score.

    budget_difference = (
        destination_df["Average_Budget"] - budget
    ).abs()

    budget_score = (
        1 -
        budget_difference /
        destination_df["Average_Budget"].max()
    ).clip(0, 1)


    # ---------------------------------------------------------
    # 2. Calculate duration similarity
    # ---------------------------------------------------------
    # An exact duration match receives a score of 1.

    duration_difference = (
        destination_df["Recommended_Trip_Duration"] -
        duration
    ).abs()

    duration_score = (
        1 -
        duration_difference /
        destination_df["Recommended_Trip_Duration"].max()
    ).clip(0, 1)


    # ---------------------------------------------------------
    # 3. Calculate season match
    # ---------------------------------------------------------
    # 1 = matching season
    # 0 = different season

    season_score = (
        destination_df["Best_Season"] == season
    ).astype(int)


    # ---------------------------------------------------------
    # 4. Calculate category match
    # ---------------------------------------------------------
    # 1 = matching category
    # 0 = different category

    category_score = (
        destination_df["Category"] == category
    ).astype(int)


    # ---------------------------------------------------------
    # 5. Normalize Adventure Score
    # ---------------------------------------------------------
    # Convert the original 2-9 scale into 0-1
    # so it can be combined with the other scores.

    adventure_score = (
        destination_df["Adventure_Score"] -
        destination_df["Adventure_Score"].min()
    ) / (
        destination_df["Adventure_Score"].max() -
        destination_df["Adventure_Score"].min()
    )


    # ---------------------------------------------------------
    # 6. Define recommendation weights
    # ---------------------------------------------------------
    # These are our baseline weights.
    #
    # Season and category are given the highest importance
    # because they represent strong user preferences.

    season_weight = 0.30
    category_weight = 0.30
    budget_weight = 0.20
    duration_weight = 0.10
    adventure_weight = 0.10


    # ---------------------------------------------------------
    # 7. Calculate final recommendation score
    # ---------------------------------------------------------

    recommendation_score = (
        season_score * season_weight
        + category_score * category_weight
        + budget_score * budget_weight
        + duration_score * duration_weight
        + adventure_score * adventure_weight
    )


    # ---------------------------------------------------------
    # 8. Create the result DataFrame
    # ---------------------------------------------------------

    results = destination_df[
        [
            "Destination",
            "State",
            "Category",
            "Best_Season",
            "Average_Budget",
            "Recommended_Trip_Duration",
            "Adventure_Score"
        ]
    ].copy()


    # Add the calculated recommendation score.

    results["Recommendation_Score"] = recommendation_score


    # ---------------------------------------------------------
    # 9. Sort destinations by recommendation score
    # ---------------------------------------------------------

    results = results.sort_values(
        by="Recommendation_Score",
        ascending=False
    )


    # ---------------------------------------------------------
    # 10. Return only the requested number of results
    # ---------------------------------------------------------

    return results.head(top_n).reset_index(drop=True)

Test The Function

In [44]:
# Test the recommendation function using our sample user.

recommendations = recommend_destinations(
    budget=25000,
    duration=4,
    season="Nov-Feb",
    category="Adventure",
    top_n=5
)

# Display the recommendations.
recommendations

,Destination,State,Category,Best_Season,Average_Budget,Recommended_Trip_Duration,Adventure_Score,Recommendation_Score
0,Goa,Goa,Beach,Nov-Feb,30000,4,6,0.628571
1,Dhanushkodi,Tamil Nadu,Coastal,Nov-Feb,30000,4,6,0.628571
2,Pondicherry,Puducherry,Coastal,Nov-Feb,30000,4,6,0.628571
3,Gokarna,Karnataka,Beach,Nov-Feb,30000,4,6,0.628571
4,Majuli Island,Assam,Island,Nov-Feb,30000,4,6,0.628571

In [45]:
# Test the recommendation system with a different user.
#
# This user wants:
# - A budget of ₹35,000
# - A 5-day trip
# - Travel during Mar-Jun
# - An Adventure destination

recommendations_2 = recommend_destinations(
    budget=35000,
    duration=5,
    season="Mar-Jun",
    category="Adventure",
    top_n=5
)

# Display the recommendations.
recommendations_2

,Destination,State,Category,Best_Season,Average_Budget,Recommended_Trip_Duration,Adventure_Score,Recommendation_Score
0,Nubra Valley,Ladakh,Adventure,Mar-Jun,35000,5,9,1.0
1,Spiti Valley,Himachal Pradesh,Adventure,Mar-Jun,35000,5,9,1.0
2,North Sikkim,Sikkim,Adventure,Mar-Jun,35000,5,9,1.0
3,Rishikesh,Uttarakhand,Adventure,Mar-Jun,35000,5,9,1.0
4,Miyar Valley,Himachal Pradesh,Adventure,Mar-Jun,35000,5,9,1.0

In [46]:
# Test another user profile.
#
# This user specifically wants:
# - A ₹30,000 budget
# - A 4-day trip
# - Nov-Feb travel
# - A Beach destination

recommendations_3 = recommend_destinations(
    budget=30000,
    duration=4,
    season="Nov-Feb",
    category="Beach",
    top_n=5
)

# Display the recommendations.
recommendations_3

,Destination,State,Category,Best_Season,Average_Budget,Recommended_Trip_Duration,Adventure_Score,Recommendation_Score
0,Goa,Goa,Beach,Nov-Feb,30000,4,6,0.957143
1,Gokarna,Karnataka,Beach,Nov-Feb,30000,4,6,0.957143
2,Hidden Goa Coves,Goa,Beach,Nov-Feb,30000,4,6,0.957143
3,Varkala,Kerala,Beach,Nov-Feb,30000,4,6,0.957143
4,Astaranga & Ramachandi,Odisha,Beach,Nov-Feb,30000,4,6,0.957143

In [47]:
# Create multiple test cases to evaluate our recommendation system.
#
# Each test case represents a different type of traveler.

test_cases = [
    {
        "name": "Adventure Traveler",
        "budget": 35000,
        "duration": 5,
        "season": "Mar-Jun",
        "category": "Adventure"
    },
    {
        "name": "Beach Traveler",
        "budget": 30000,
        "duration": 4,
        "season": "Nov-Feb",
        "category": "Beach"
    },
    {
        "name": "Heritage Traveler",
        "budget": 25000,
        "duration": 3,
        "season": "Oct-Mar",
        "category": "Heritage"
    },
    {
        "name": "Spiritual Traveler",
        "budget": 25000,
        "duration": 3,
        "season": "Oct-Mar",
        "category": "Spiritual"
    }
]

# Display the test cases so we can verify them.
pd.DataFrame(test_cases)

                 name  budget  duration   season   category
0  Adventure Traveler   35000         5  Mar-Jun  Adventure
1      Beach Traveler   30000         4  Nov-Feb      Beach
2   Heritage Traveler   25000         3  Oct-Mar   Heritage
3  Spiritual Traveler   25000         3  Oct-Mar  Spiritual

In [48]:
# Run the recommendation system for every test case.
#
# We will store the best recommendation and its score
# so that we can compare the results easily.

evaluation_results = []

for test in test_cases:

    # Generate recommendations using the current test case.
    recommendations = recommend_destinations(
        budget=test["budget"],
        duration=test["duration"],
        season=test["season"],
        category=test["category"],
        top_n=5
    )

    # Get the highest-ranked recommendation.
    best = recommendations.iloc[0]

    # Store the evaluation information.
    evaluation_results.append({
        "Test Case": test["name"],
        "Requested Category": test["category"],
        "Requested Season": test["season"],
        "Best Recommendation": best["Destination"],
        "Recommended Category": best["Category"],
        "Recommended Season": best["Best_Season"],
        "Recommendation Score": best["Recommendation_Score"]
    })


# Convert the evaluation results into a DataFrame.
evaluation_df = pd.DataFrame(evaluation_results)

# Display the evaluation results.
evaluation_df

,Test Case,Requested Category,Requested Season,Best Recommendation,Recommended Category,Recommended Season,Recommendation Score
0,Adventure Traveler,Adventure,Mar-Jun,Nubra Valley,Adventure,Mar-Jun,1.000000
1,Beach Traveler,Beach,Nov-Feb,Goa,Beach,Nov-Feb,0.957143
2,Heritage Traveler,Heritage,Oct-Mar,Jaipur,Heritage,Oct-Mar,0.897143
3,Spiritual Traveler,Spiritual,Oct-Mar,Varanasi (Kashi),Spiritual,Oct-Mar,0.840000